"""Create messages table

Revision ID: 39b1e0d16c2c
Revises: 5f9da97bcb9f
Create Date: 2025-06-24 11:15:10.353961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b1e0d16c2c'
down_revision = '5f9da97bcb9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
